[package]
name = "csv2wf"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Lowe"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
clap = { version = "4.1.4", features = ["derive"] }
